<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace FullCalendar;

use Thelia\Module\BaseModule;
use Propel\Runtime\Connection\ConnectionInterface;
use Thelia\Install\Database;

/**
 * Class FullCalendar
 * @package FullCalendar
 */
class FullCalendar extends BaseModule
{
    const MESSAGE_DOMAIN = "fullcalendar";
    const ROUTER = "router.fullcalendar";

    /**
     * Get a module's configuration variable
     *
     * @param  string $variableName the variable name
     * @param  string $defaultValue the default value, if variable is not defined
     * @param  null $valueLocale the required locale, or null to get default one
     * @return string the variable value
     */
    public static function getConfigValue($variableName, $defaultValue = null, $valueLocale = null)
    {
        return parent::getConfigValue($variableName, "en_US", $valueLocale);
    }

    /**
     * Set module configuration variable, creating it if required
     *
     * @param  string $variableName the variable name
     * @param  string $variableValue the variable value
     * @param  null $valueLocale the locale, or null if not required
     * @param  bool $createIfNotExists if true, the variable will be created if not already defined
     * @throws \LogicException if variable does not exists and $createIfNotExists is false
     * @return $this;
     */
    public static function setConfigValue($variableName, $variableValue, $valueLocale = null, $createIfNotExists = true)
    {
        parent::setConfigValue($variableName, $variableValue, "en_US", $createIfNotExists);
    }


}
