<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace FullCalendar\Event\Module\Base;

/**
 * Class FullCalendarEvents
 * @package FullCalendar\Event\Module\Base
 * @author TheliaStudio
 */
class FullCalendarEvents
{
}
