<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace FullCalendar\Form\Base;

use FullCalendar\FullCalendar;
use Thelia\Form\BaseForm;
use FullCalendar\Model\Config\FullCalendarConfigValue;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * Class FullCalendarConfigForm
 * @package FullCalendar\Form\Base
 * @author TheliaStudio
 */
class FullCalendarConfigForm extends BaseForm
{
    const FORM_NAME = "fullcalendar_config_form";

    /**
     *
     * in this function you add all the fields you need for your Form.
     * Form this you have to call add method on $this->formBuilder attribute :
     *
     * $this->formBuilder->add("name", "text")
     *   ->add("email", "email", array(
     *           "attr" => array(
     *               "class" => "field"
     *           ),
     *           "label" => "email",
     *           "constraints" => array(
     *               new \Symfony\Component\Validator\Constraints\NotBlank()
     *           )
     *       )
     *   )
     *   ->add('age', 'integer');
     *
     * @return null
     */
    protected function buildForm()
    {
        $translationKeys = $this->getTranslationKeys();
        $fieldsIdKeys = $this->getFieldsIdKeys();

        $this->addEnablePreventScrollField($translationKeys, $fieldsIdKeys);
    }

    protected function addEnablePreventScrollField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder
            ->add("enable_prevent_scroll", "checkbox", array(
                "label" => $this->readKey("enable_prevent_scroll", $translationKeys),
                "label_attr" => [
                    "for" => $this->readKey("enable_prevent_scroll", $fieldsIdKeys),
                    "help" => $this->readKey("help.enable_prevent_scroll", $translationKeys)
                ],
                "required" => false,
                "constraints" => array(
                ),
                "value" => FullCalendar::getConfigValue(FullCalendarConfigValue::ENABLE_PREVENT_SCROLL, false),
            ))
        ;
    }

    public function getName()
    {
        return static::FORM_NAME;
    }

    public function readKey($key, array $keys, $default = '')
    {
        if (isset($keys[$key])) {
            return $keys[$key];
        }

        return $default;
    }

    public function getTranslationKeys()
    {
        return array();
    }

    public function getFieldsIdKeys()
    {
        return array(
            "enable_prevent_scroll" => "enable_prevent_scroll",
        );
    }
}
