<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace FullCalendar\Form;

use FullCalendar\FullCalendar;
use FullCalendar\Form\Base\FullCalendarConfigForm as BaseFullCalendarConfigForm;

/**
 * Class FullCalendarConfigForm
 * @package FullCalendar\Form\Base
 */
class FullCalendarConfigForm extends BaseFullCalendarConfigForm
{
    public function getTranslationKeys()
    {
        return array(
            "enable_prevent_scroll" => $this->translator->trans("Enable prevent scroll", [], FullCalendar::MESSAGE_DOMAIN),
            "help.enable_prevent_scroll" => $this->translator->trans("If this is checked, all the calendars won't manager their size themselves", [], FullCalendar::MESSAGE_DOMAIN),
        );
    }
}
