<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace FullCalendar\Event\Module;

use FullCalendar\Event\Module\Base\FullCalendarEvents as BaseFullCalendarEvents;

/**
 * Class FullCalendarEvents
 * @package FullCalendar\Event\Module
 * @author TheliaStudio
 */
class FullCalendarEvents extends BaseFullCalendarEvents
{
}
