<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace FullCalendar\Controller;

use FullCalendar\Controller\Base\FullCalendarConfigController as BaseFullCalendarConfigController;

/**
 * Class FullCalendarConfigController
 * @package FullCalendar\Controller
 */
class FullCalendarConfigController extends BaseFullCalendarConfigController
{
}
